#
# Jekyll config
# ==============================================================================



# Globals
# ------------------------------------------------------------------------------

exclude: ['images', 'scripts']



# Site
# ------------------------------------------------------------------------------

name: Group 6 Technologies
description: End to end television, post production, and broadcast facility solutions



# Page Defaults
# ------------------------------------------------------------------------------

defaults:
