#
# Jekyll config
# ==============================================================================



# Globals
# ------------------------------------------------------------------------------

exclude: ['images', 'scripts']
future: true

# Plugins
# ------------------------------------------------------------------------------

plugins:
  - jekyll-sitemap


# Site
# ------------------------------------------------------------------------------

name: Group 6 Technologies
description: End to end television, post production, and broadcast facility solutions
url: "https://www.group6.co.nz"


# Page Defaults
# ------------------------------------------------------------------------------

defaults:
